process.env.EVENT_OAUTH_TOKEN = 'AWXQ6FOPFWLQBPAIORNZ';
process.env.EVENT_CLIENT_SECRET = 'ITATE5HGD4DYT4IB6MJQIB67ZALROSPVXVI64JFKECOXRJ3VVV';
process.env.MAPBOX_TOKEN = 'pk.eyJ1IjoiY2RraXJrd29vZCIsImEiOiJjamQxd3FvOXIzNTlyMnFvNXR6Mm01MDAyIn0.BCM8hKEDvO7OdM_nBboPWA';
